# Generated by Django 5.2.8 on 2025-12-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_group_activity_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='group',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
