# Generated by Django 5.2.8 on 2025-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_file_group_remove_file_user_delete_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
