# Generated by Django 5.2.8 on 2025-12-09 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_token_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('banned_until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
