# Generated by Django 5.2.8 on 2025-12-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_apipermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipermission',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='apipermission',
            unique_together={('codename', 'group')},
        ),
    ]
